### ISSUE TITLE
Injecting ISO country code not working in Symfony 3.1.3

### ISSUE THREAD

**Issue by fdyckhoff** [barbieswimcrew/zip-code-validator#1]
Maybe I'm using it wrong but I cannot get this constraint to work in my Symfony 3.1.3 application.

I tried following configurations:

```
    /**
     * @ZipCode("DE")
     */
    protected $zipCode;
```

and 

```
    /**
     * @ZipCode(iso="DE")
     */
    protected $zipCode;
```

Both did not work... My request results in a PHP Notice: "Undefined index:". (see screenshot)

The ISO code used in the validator to fetch the pattern is still NULL...

```
216. $pattern = $this->patterns[$constraint->getIso()]; 
```

![notice-undefined-index](https://cloud.githubusercontent.com/assets/14044108/17418351/6d27e99c-5a98-11e6-9211-82fd144c06d6.png)

**Comment by barbieswimcrew** [comment]
Got that fixed right now. in release v1.0.2. Hope it will work now as expected by injecting the iso code like this:

``` bash
@ZipCode(iso="DE")
```
