### ISSUE TITLE
Allow to use empty zip code when getter is set

### ISSUE THREAD

**Issue by clash82** [barbieswimcrew/zip-code-validator#10]
It's sad that it's not possible to use empty value for the zip code when `getter` is set. Right now, when I select country but I don't want to fill the zip code then error message is shown. Can we do something with that? I only want to validate field if it has some value and omit validation when field is empty.

btw, great library, thank you for your work.

**Comment by barbieswimcrew** [comment]
Thanks for requesting this feature, I will consider this!

**Comment by barbieswimcrew** [comment]
Implemented option "ignoreEmpty" (bool, default: false) that should get that work. Already released that in v1.1.0 - please let me know if that's what you're looking for. Thanks!

**Comment by clash82** [comment]
Works like a charm. Thank you!
