### ISSUE TITLE
Update FR pattern

### ISSUE THREAD

**Issue by Neirda24** [barbieswimcrew/zip-code-validator#11]
Hi.

Some french zip code coul also be `2BXXX` or `2AXXX`.
So the pattern should shift from `\\d{2} ?\\d{3}` to `\\d{1}(?:A|B|\\d{1}) ?\\d{3}`

Thanks.

**Comment by barbieswimcrew** [comment]
Thanks for your request, solved that in tag v1.0.9

**Comment by Neirda24** [comment]
Great thanks. When will it be released ?

**Comment by barbieswimcrew** [comment]
Already released ;-)

**Comment by Neirda24** [comment]
Whoaa !! GG
