### ISSUE TITLE
United Arab Emirates

### ISSUE THREAD

**Issue by simoheinonen** [barbieswimcrew/zip-code-validator#12]
> Dubai is a city/state in United Arab Emirates, and the U.A.E. does not use a ZIP/PIN code or its equivalent. Instead, Post Office Box numbers are used. These do not correspond to geographic locations, but numbered mailboxes to which mail is delivered and can then be collected by the person(s)/company using that Post Box.

https://www.quora.com/What-is-the-ZIP-code-of-Dubai

Should we consider an empty value as valid?

**Comment by simoheinonen** [comment]
Actually I guess using `strict=false` would solve this..

**Comment by barbieswimcrew** [comment]
United Arab Emirates have P.O. Box numbers defined by 5 digits like 12345, right? In that case a validation for ISO 3166-2 code "UA" is already defined: 

`'UA' => '\\d{5}'`

Is that just fine or is there anything that has to be modified?

**Comment by simoheinonen** [comment]
`UA` is Ukraine, United Arab Emirates is `AE` which is missing. I've only seen empty values so for my case using `ignoreEmpty=true` will solve it. This can probably be closed

**Comment by barbieswimcrew** [comment]
Well, you're absolutely right... was my mistake, sorry. AE! Okay, won't add it if ignoreEmpty=true works for you. Thanks anyway!
