### ISSUE TITLE
Hong Kong and Macao

### ISSUE THREAD

**Issue by simoheinonen** [barbieswimcrew/zip-code-validator#13]
> The postal code for Hong Kong is 999077, and Macau 999078. 

https://en.wikipedia.org/wiki/List_of_postal_codes_in_China

Or I suppose it can be just empty too

**Comment by barbieswimcrew** [comment]
Hongkong seems to have it's own ISO-3166-2 code which is HK and Macau has MO, correct? If those will be used I suggest that I'm going to add both iso codes with its postal codes you mentioned. Would that be okay for you?

**Comment by simoheinonen** [comment]
Same as UAE, using `ignoreEmpty=true` solved this for me. I suppose it wouldn't hurt to have those though but I guess they are rarely used

**Comment by barbieswimcrew** [comment]
added HK and MO with release tag v1.1.1 - thanks for your help!
