### ISSUE TITLE
Is this library exclusively for symfony projects?

### ISSUE THREAD

**Issue by davalb** [barbieswimcrew/zip-code-validator#22]
I see that this library uses some Symfony classes, but is it for use in symfony projects only? Your read.me file does not mention symfony and you have not attached the symfony tag.

**Comment by barbieswimcrew** [comment]
Hi @davalb, the zip code validator library requires the [Symfony Validator component](https://symfony.com/doc/current/components/validator.html) which can be required standalone into any php project. Hope this will help, kind regards
