### ISSUE TITLE
Replace mockery by phpunit

### ISSUE THREAD

**Issue by barbieswimcrew** [barbieswimcrew/zip-code-validator#27]
For sure, mockery is a valid php unit testing framework. But for some reasons using PHPUnit as unit testing framework would be quite more "standard" and "state of the art". Therefor it would be great to replace the Mockery dependency by using the newest stable PHPUnit version and to write all existing tests in PHPUnit as well.

Furthermore the unit tests shall be separated to have "one class by file". This means to move the fake objects which are currently part of the testfiles itself in separate files. 

All those changes would improve the quality of this project.

**Comment by dangenendt** [comment]
I'll do this one

**Comment by dangenendt** [comment]
After closer examination of the classes and using PHPUnit, unit tests only make moderate sense here. 
Because the validators don't return any data, you can't make meaningful assertions. 
Without any assertions you get PhpUnit messages ala

> There were 1 risky tests:
> 1) NlZipCodeValidatorTest::it_validates_a_nl_zip_code_with_iso
> This test did not perform any assertions

Personally I would suggest some refactorings before testing units.
Just my 2 cents

**Comment by barbieswimcrew** [comment]
I was expecting that the currently existing tests could cause some confusion because of some weird Mockery stuff... That‘s why it‘s mandatory to replace it. If you think we should refactor the tests we should do that!

**Comment by dangenendt** [comment]
Ok, i'll see what I can do.

**Comment by dangenendt** [comment]
PR ready
#28

**Comment by barbieswimcrew** [comment]
Well done, thanks for your contribution and your help!
