### ISSUE TITLE
1.0.3 not available in packagist

### ISSUE THREAD

**Issue by mikeyudin** [barbieswimcrew/zip-code-validator#3]
Hello,

Trying to add 1.0.3 via composer, but it's not available in packagist.  Can you take a look at this?

Thanks!

**Comment by barbieswimcrew** [comment]
Hi,

due to some issues syncing the tags with packagist I had to create a new tag v1.0.4 so please try to add this version via composer and let me know if there are still troubles.

Kind regards!
