### ISSUE TITLE
Swiss postal codes allowing 0xxx

### ISSUE THREAD

**Issue by Toflar** [barbieswimcrew/zip-code-validator#32]
Hi, thanks for this cool little validator!

I noticed that `0000` is considered a valid zip code for Switzerland (`CH`), however, the lowest allowed is `1000`.

Here's a list of valid codes: https://postleitzahlenschweiz.ch/tabelle/ (sorry, no English version but I guess the table is okay 😄 )

We could update the regex to only allow 1-9 as the first digit but I was not sure how you want to go about this as it seems like you're using some appspot source.

**Comment by barbieswimcrew** [comment]
Hi @Toflar and thanks for your issue. You are totally right, it seems the zip code regex for Switzerland does allow more than it already should. 

If you like please create a new pull request to solve that. Have a look to the following PR will get you all information you need on how this should look like. Please don't forget a unit test to make sure that your changes and even the other swiss specific cases will work properly:

https://github.com/barbieswimcrew/zip-code-validator/pull/29/files

Thanks in advance!

**Comment by Toflar** [comment]
Sure, I was just not sure about that comment regarding the appspot source.
Done: https://github.com/barbieswimcrew/zip-code-validator/pull/33

**Comment by barbieswimcrew** [comment]
Thanks for your contribution. Merged and released:
https://github.com/barbieswimcrew/zip-code-validator/releases/tag/v1.3.4

**Comment by Toflar** [comment]
Thank you!
