### ISSUE TITLE
Strange validation for JM

### ISSUE THREAD

**Issue by aschempp** [barbieswimcrew/zip-code-validator#34]
Thanks a lot for this library! I just copied all regexps into my javascript frontend and stubled upon a strange validation: https://github.com/barbieswimcrew/zip-code-validator/blob/master/src/ZipCodeValidator/Constraints/ZipCodeValidator.php#L114

`'[\\a-zA-Z]{2}'`

Should this validate for two letter upper lowercase? What's the backslash for? Just asking to potentially fix an issue, I don't need JM at all 😉

**Comment by barbieswimcrew** [comment]
Hi @aschempp, thanks for your message. The author of the Jamaica regex PR @boxblinkracer intended to validate against two letters - no matter in what case they are. He also committed a unit test for Jamaica zip code validation, thus for me it looks as if everything might be fine at the moment.

Regarding the double backslash... the appspot source noticed in my code returns regexp with double backslashes. Seems to work, though. :-)

**Comment by aschempp** [comment]
yeah, I noticed the (kinda unnecessary) double backslashes as well. But in this case the regex would should be converted to `[\a-zA-Z]`, which either means `\a` as a special operation (I only know `\d` for digits etc.), or it also allows a backslash in the list of characters.

**Comment by aschempp** [comment]
see https://github.com/barbieswimcrew/zip-code-validator/pull/35
