### ISSUE TITLE
Translate message

### ISSUE THREAD

**Issue by hous04** [barbieswimcrew/zip-code-validator#36]
Hi
In fact this is not an issue but I'd like to know if can I translate the error message "This value is not a valid ZIP code." to french ?

Thanks

**Comment by barbieswimcrew** [comment]
Hi @hous04, just as a matter of interest - did you solve your question on your own or may I help you in some way?

**Comment by hous04** [comment]
Hi
Yes , I put the message like this , it works fine
` * @ZipCode(getter="getCountry", message="le code postal n'est pas valide")`

**Comment by barbieswimcrew** [comment]
Awesome! And if you like, just try to put an translation alias instead of the message itself and you will be able to use the symfony translations (like messages.fr.yaml)
