### ISSUE TITLE
Disclaim that it only validates the pattern not the existence

### ISSUE THREAD

**Issue by patrick-mcdougle** [barbieswimcrew/zip-code-validator#37]
It should probably be disclaimed that this library only validates the zipcode against a pattern and does not validate whether a given zip code exists. ~42,000 of the 100,000 possible 5-digit ZIP codes are currently in use by the USPS. This nuance could matter for some applications.

**Comment by barbieswimcrew** [comment]
Hi @patrick-mcdougle you may be right, yes. Might you please edit the README file the way you suggested? Thank you in advance and kind regards.
