### ISSUE TITLE
Swiss Postcode format old

### ISSUE THREAD

**Issue by ychadwick** [barbieswimcrew/zip-code-validator#40]
Hi there,

I think it would be good for you to update your postcode regex, the postcodes in Switzerland are 4 digits and not 3.

Otherwise, thanks for the great little bundle.

**Comment by barbieswimcrew** [comment]
Hi @ychadwick and thanks for your message. I guess you might be a little confused regarding the postcode regex of Switzerland. The regex currently looks like:

[1-9]\\d{3}

Which means in detail: the first digit has to between 1 and 9 (so 0 not allowed) followed by 3 further digits.

Looks like correct, doesn't it?
