### ISSUE TITLE
Get ISO from other formType

### ISSUE THREAD

**Issue by LauLaman** [barbieswimcrew/zip-code-validator#43]
I would like to create a multi-county form where the user selects the country. 

The iso should be used set by another form type so that when i am selecting Belgium it validates and when i select The Netherlands it also validates

Symfony has the [CountryType](https://symfony.com/doc/current/reference/forms/types/country.html) already build in.

It would be nice to use it like this:
```php
/**
 * @ZipCode(iso="AUTO")
 */
```

In this case we look in the form for the CountryType and use its value

**Comment by barbieswimcrew** [comment]
Hi, did you already check the docs?

https://github.com/barbieswimcrew/zip-code-validator#use-a-getter-to-inject-the-country-code-dynamically

Maybe this will help you? Let me know.

**Comment by barbieswimcrew** [comment]
@LauLaman did that solve your issue? Let me know, thanks!
