### ISSUE TITLE
PHP 8.1 deprecates passing null to strtoupper()

### ISSUE THREAD

**Issue by CodeCasterNL** [barbieswimcrew/zip-code-validator#45]
See [PHP RFC: Deprecate passing null to non-nullable arguments of internal functions](https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg). This code:

https://github.com/barbieswimcrew/zip-code-validator/blob/e7fb22a69568304629f482118ea67d6786b6b4a9/src/ZipCodeValidator/Constraints/ZipCodeValidator.php#L231

Triggers a deprecation:

> Deprecated: strtoupper(): Passing null to parameter #&#x2060;1 ($string) of type string is deprecated

Change it to:

```php
if (null === $constraint->iso || empty($iso = strtoupper($constraint->iso))) {
```
?

**Comment by barbieswimcrew** [comment]
@CodeCasterNL or maybe like this?
` if (!($iso = strtoupper((string)$constraint->iso))) { `
