### ISSUE TITLE
Allow PHP8-Attributes

### ISSUE THREAD

**Issue by Chris53897** [barbieswimcrew/zip-code-validator#48]
Allow usage with PHP8-Attributes.
Could be added after this PR is merged. https://github.com/barbieswimcrew/zip-code-validator/pull/47

#[ZipCode(getter: 'getCountry')]

Could be something like this in the code.
But i guess the __construct() needs to be changed.

`namespace ZipCodeValidator\Constraints;

use Attribute;
use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\Exception\MissingOptionsException;

/**
 * @Annotation
 * @Target({"PROPERTY", "METHOD", "ANNOTATION"})
 * @NamedArgumentConstructor
 * @author Martin Schindler
 */
#[Attribute(Attribute::TARGET_PROPERTY | Attribute::TARGET_METHOD)]
class ZipCode extends Constraint`

**Comment by Pixelshaped** [comment]
Hello! Interested in this, can eventually provide the PR if maintainers are active.

**Comment by barbieswimcrew** [comment]
@Pixelshaped sure, feel free to submit your PR 👍

**Comment by Pixelshaped** [comment]
Will probably do it next week if @Chris53897 isn't faster (I've seen you just submited the PR #49 ) :)
