### ISSUE TITLE
Customize constraint message

### ISSUE THREAD

**Issue by astronati** [barbieswimcrew/zip-code-validator#54]
## The problem

The error message "This value is not a valid ZIP code" should be customizable.

## Proposed Solution
`$message` property should be part of the constructor params.

### Pro
Being editable when the validator is used as attribute
`#[ZipCode(['iso' => 'IT', 'message' => 'custom error message'])]`

**Comment by barbieswimcrew** [comment]
@astronati as far as I understand `#[ZipCode(['iso' => 'IT', 'message' => 'custom error message'])]` should work out of the box, shouldn't it? You inject an array of options which will then automatically be mapped. 

Please check the `__construct` of the `abstract class Constraint`... it looks as follows:

```php
    public function __construct(mixed $options = null, ?array $groups = null, mixed $payload = null)
    {
        unset($this->groups); // enable lazy initialization

        $options = $this->normalizeOptions($options);
        if (null !== $groups) {
            $options['groups'] = $groups;
        }
        $options['payload'] = $payload ?? $options['payload'] ?? null;

        foreach ($options as $name => $value) {
            $this->$name = $value; // <--- this is where the magic happens
        }
    }
```

Please let me know, thanks! ;-)

**Comment by astronati** [comment]
@barbieswimcrew thanks for replying me.

**Comment by norkunas** [comment]
Symfony is going to deprecate passing options as array in all of their constraints (see https://github.com/symfony/symfony/pull/54744), and I think this should follow same path

**Comment by barbieswimcrew** [comment]
> Symfony is going to deprecate passing options as array in all of their constraints (see [symfony/symfony#54744](https://github.com/symfony/symfony/pull/54744)), and I think this should follow same path

You're right, let's keep that in mind for the future!
