### ISSUE TITLE
Feature: Symfony Form connected to Country Form

### ISSUE THREAD

**Issue by Hanmac** [barbieswimcrew/zip-code-validator#56]
I don't know if it fits into this Repo, but I would like to see a Symfony Form Field, that can be connected to a Country Form Field.
And then, via JS, updates the Regexp String used to validate the ZipCode Field.

With that, the User can see if the ZipCode is going to be valid for the Selected Country Field, before the Data is submitted.

**Comment by barbieswimcrew** [comment]
@Hanmac thanks for your feature request. Please have a look at this project: https://github.com/SymfonyCasts/dynamic-forms 

That should meet your needs, right? ✌️

**Comment by Chris53897** [comment]
See https://ux.symfony.com/demos/live-component/dependent-form-fields for a demo.
